### ISSUE TITLE
start-dev mode

### ISSUE THREAD

**Issue by benycode** [eabykov/keycloak-compose-v2#3]
Hello,

is it possible to have same auto import without start-dev?

what is a risk using start-dev in prod?

Thank you :)

**Comment by eabykov** [comment]
1. Yes, its possible to import realm not in the dev mode: https://www.keycloak.org/server/importExport `start --import-realm`
2. In short: `no risk`, detailed description here: https://www.keycloak.org/server/configuration

start-dev
- HTTP is enabled
- Strict hostname resolution is disabled
- Cache is set to local (No distributed cache mechanism used for high availability)
- Theme-caching and template-caching is disabled

start
- HTTP is disabled as transport layer security (HTTPS) is essential
- Hostname configuration is expected
- HTTPS/TLS configuration is expected
